package com.inspify.locators;

import org.openqa.selenium.By;

public interface AdvisorPageLocators {
	
	By STARTSESSION_BUTTON = By.xpath("//button[normalize-space(text())='Start Session']");
	By NAME_INPUTFIELD = By.cssSelector("input.input-alias");
	By ADVISORROLE_ICONS = By.xpath("//div[contains(@class,'group-item primary-group')]");
	By ADMIT_BUTTON = By.xpath("//div[normalize-space(text())='Admit']");
	By DISPLAY_NAME = By.cssSelector("#local-wrapper div.display-name");
	By SEARCH_ICON = By.xpath("//div[@id='searchProduct']");
	By COMPAREPRODUCTS_ICON_INMEETINGCONTROLLER = By.xpath("//div[@id='compareProduct']");
	By SEARCHSTORIES_ICON_INMEETINGCONTROLLER = By.xpath("//div[@id='searchStories']");
	By IFRAMECONTAINER = By.cssSelector("#content-popup");
	By PRODUCTSEARCH_PAGETITLE = By.xpath("//span[normalize-space(text())='PRODUCT SEARCH']");
	By SEARCH_INPUT = By.cssSelector(".keywords-input>input");
	By SEARCH_CLEAR = By.cssSelector(".keywords-input>input+svg");
	By SEARCH_BUTTON = By.cssSelector(".keywords-input button");
	By PRODUCTSPOPUP_CROSSICON = By.cssSelector("button.close");
	By SIDEMENUNAVIGATOR_ICON = By.cssSelector("button.slidenav-icon");
	By PRODUCTSEARCH_MENUITEM = By.cssSelector("button.nav-search");
	By STOPMEETING_BUTTON = By.cssSelector("#meetingEndButton");
	By ENDMEETING_BUTTON = By.xpath("//button[normalize-space(text())='END MEETING']");
	By FIRSTPRODUCT_MODELTITLE = By.cssSelector("#showcase-0 .prod-title");
	By ALLPRODUCTSMODELTITLE = By.cssSelector(".prod-title");
	By PRODUCTCOMPARE_MENUITEM = By.cssSelector("button.nav-compare");
	By COMPAREPRODUCTS_PAGETITLE = By.xpath("//span[normalize-space(text())='COMPARE PRODUCTS']");
	By EMPTYMESSAGE_COMPAREPRODUCTSPOPUP_TEXT = By.xpath("//h3[normalize-space(text())=\"You don't have any products to be compared\"]");
	By SEARCHPRODUCTS_BUTTON = By.xpath("//button[normalize-space(text())='SEARCH PRODUCTS']");
	By STARTCOMPARE_PRODUCTS_BUTTON = By.xpath("//button[contains(text(),'START TO COMPARE')]");
	By DELETECOMPAREPRODUCTS_CROSSICON = By.cssSelector("button.remove-btn");
	By PRODUCTCOMPARE_SIDEBAR_MESSAGE = By.cssSelector("div.compare-sidebar>p");
	By PRODUCTCOMPARE_SIDEBAR_SECTION = By.cssSelector("div.compare-sidebar");
	By ADDPRODUCTTO_COMPARE_BUTTON = By.cssSelector("span.add-product");
	By PRODUCTDETAILS_PAGETITLE = By.xpath("//span[normalize-space(text())='PRODUCT DETAILS']");
	By PRODUCT_MODEL_CODE = By.cssSelector(".modelcode");
	By PRODUCT_NAME = By.tagName("h1");
	By PRODUCTDETAILS_COMPAREPRODUCT_BUTTON = By.xpath("//a[normalize-space(text())='Compare Product']");
	By FIRSTPRODUCT_MODELTEXT = By.cssSelector("#showcase-0 .prod-model");
	By DESCRIPTIONSECTION = By.xpath("//span[normalize-space(text())='Description']");
	By SPECIFICATIONSSECTION = By.xpath("//span[normalize-space(text())='Specifications']");
	By DESCRIPTIONSECTION_COLLAPSED = By.xpath("//span[normalize-space(text())='Description']/../following-sibling::div[@class='hide collapse']");
	By DESCRIPTIONSECTION_EXPANDED = By.xpath("//span[normalize-space(text())='Description']/../following-sibling::div[contains(@class,'show collapse')]");
	By DESCRIPTIONTEXT = By.cssSelector(".descriptions-container");
	By SPECIFICATIONSECTION_COLLAPSED = By.xpath("//span[normalize-space(text())='Specifications']/../following-sibling::div[@class='hide collapse']");
	By SPECIFICATIONSECTION_EXPANDED = By.xpath("//span[normalize-space(text())='Specifications']/../following-sibling::div[contains(@class,'show collapse')]");
	By SPECIFICATIONSTEXT = By.cssSelector(".specifications-container");
	By PRODUCTIMAGECAROUSEL_ITEM = By.cssSelector(".slider-container li.react-multi-carousel-item");
	By PRODUCTIMAGECAROUSEL_RIGHTSIDE_BUTTON = By.xpath("(//button[contains(@class,'arrow--right')])[1]");
	By PRODUCTIMAGECAROUSEL_LEFTSIDE_BUTTON = By.xpath("(//button[contains(@class,'arrow--left')])[1]");
	By COLOR_VARIATIONS = By.xpath("(//div[contains(@class,'colors')]/img)");
	By PRODUCT_PRICE = By.xpath("//h1/following-sibling::p[contains(@class,'price')]");
	By PRODUCT_DESCRIPTIONTEXT=By.cssSelector(".descriptions-container");
	By PRODUCT_SPECIFICATIONTEXT= By.cssSelector(".specifications-container");
	By YOUMAYALSOLIKE_FIRSTPRODUCT = By.xpath("(//section[contains(@class,'similar-products')]//li[contains(@class,'react-multi-carousel-item--active')]//div)[1]");
	By YOUMAYALSOLIKE_SECTION = By.cssSelector("section.similar-products");
	By INSPIRATION_SECTION = By.cssSelector("#inspirationsslider .section-container");
	By INSPIRATION_IMAGE = By.xpath("//div[contains(@class,'inspirations-list')]//li[contains(@class,'react-multi-carousel-item--active')]");
	By INSPIRATIONIMAGECAROUSEL_ITEM = By.cssSelector(".inspirations-list li.react-multi-carousel-item");
	By INSPIRATIONIMAGECAROUSELITEM_RIGHTSIDE_BUTTON = By.cssSelector(".product-inspirations button.react-multiple-carousel__arrow--right");
	By PRODUCTSPAGEBACK_BUTTON = By.cssSelector("span.prev");
	By ABOUT_STORY_TITLE = By.tagName("h1");
	By ABOUTSTORY_DESCRIPTION = By.xpath("//P[@id='ijxbg']");
	By IDENTIFY_PAGETITLE = By.cssSelector("span.pagetitle");
	By WATCHESCOLLECTION_MENUITEM = By.cssSelector("button.nav-feedback");
	By WATCHESCOLLECTION_HEADER_TEXT = By.xpath("//p[normalize-space(text())='PILOT’S WATCHES COLLECTION']");
	By CHOPARDDASHBOARD_ICON = By.cssSelector("button.btn-express");
	By INTRODUCTION_MENU = By.xpath("//button[normalize-space(text())='Introduction']");
	By DASHBOARDCONTAINER_MENU = By.cssSelector(".container");
	By PRESENTATIONCONTAINER = By.cssSelector(".DocumentViewer");
	By SLIDELIST = By.cssSelector(".PageList");
	By MICROPHONEMUTE_MESSAGE = By.cssSelector("div.ntf-label");
	By PRESENTATIONPOPUP_CROSSICON = By.cssSelector(".popup-control button.btn:nth-child(3)");
	By IMAGESOURCE = By.cssSelector(".DocumentViewer .DocumentPage > img");
	By VIDEOSOURCE = By.cssSelector(".DocumentViewer .DocumentPage video");
	By AUDIO_UNMUTE_TEXT = By.xpath("//span[normalize-space()='Unmute My Mic']");
	By AUDIO_MUTE_TEXT = By.xpath("//span[normalize-space()='Mute My Mic']");
	By MEETING_CONTROLBUTTON = By.cssSelector("div.control-hide-button");
	By NOTIFICATION_BAR = By.cssSelector("div.ntf-content");
	By SLIDE_COUNT = By.cssSelector(".thumbnail");
	By ACTIONCONTAINERMENU_ITEM = By.cssSelector(".action-groups");
	By STORYSEARCH_ICON =By.xpath("//div[@id='searchStories']");
	By STORYSEARCH_PAGETITLE = By.xpath("//span[normalize-space(text())='STORY SEARCH']");
	By FILTER_ICON = By.cssSelector(".input-group-prepend .btn-dark:nth-child(1)");
	By STORYFILTER_SECTION = By.cssSelector(".StoryFilters");
	By FILTERPOPUP_CLOSEBUTTON = By.xpath("//button[normalize-space(text())='CLOSE']");
	By INSTAGRAM_PAGETITLE = By.xpath("//span[normalize-space(text())='INSTAGRAM']");
	By VIDEOCLIP_PAGETITLE = By.xpath("//span[normalize-space(text())='VIDEO CLIP']");
	By STORIES_DESCRIPTION = By.cssSelector("p:nth-child(1)");
	By CLEAR_SEARCHTEXT = By.cssSelector("svg.clear");
	By RESETFILTER_BUTTON = By.xpath("//button[normalize-space(text())='RESET FILTER']");
	By STORYSEARCH_SEARCHICON = By.cssSelector(".keywords-input .input-group-append>button");
	By ALLSTORIES_TITLE = By.cssSelector(".results-col .row .item span");
	By DOCUMENT_VIEWER =  By.cssSelector("#openDocument");
	By TOOLTIP_SECTION = By.cssSelector("#ToolTipWrapper");
	By GUESTS_WAITING_INLOUNGE_NAME = By.cssSelector("div.remote-users-list ul > li:nth-child(1)");
	By VIDEO_DOCUMENT = By.cssSelector(".video-document");
	By CONTENTVIEWER_IMAGE_DOCUMENT = By.xpath("//*[normalize-space(text())='INSPIFY Remote Selling']");
	By CONTENTVIEWER_VIDEO_DOCUMENT = By.xpath("//*[normalize-space(text())='Inspify_file']");
	By CAMERANOT_ACCESSIBLE_TEXT = By.xpath("//p[normalize-space(text())='Your camera is not accessible at the moment.']");
	By STARTSESSION_WITHOUTCAMERA_BUTTON = By.xpath("//button[normalize-space(text())='Start Session without camera']");
	By INMEETING_CAMERA_STATE = By.cssSelector(".MainControls #meetingVideoControl.video.muted-warning");
	By LOUNGE_CAMERABUTTON_ENABLED = By.cssSelector("div.btn-toggle div:nth-child(1)");
	By LOUNGE_CAMERABUTTON_DISABLED = By.cssSelector("div.btn-toggle div:nth-child(2)");
	By LOUNGE_CAMERABUTTON_ACTIVE = By.cssSelector("div.btn-toggle div.meeting-button.active");
	By LOCALWRAPPER_VIDEO_ID = By.cssSelector("div#local-wrapper > div");
	By INMEETING_CAMERA_BUTTON = By.cssSelector("div#meetingVideoControl");
	By CONTROL_MENUITEM = By.cssSelector("div#moreMenu");
	By INVITE_PEOPLE = By.xpath("//div[@id='ToolTipWrapper']//span[normalize-space(text())='Invite People']");
	By COPY_URL = By.xpath("//div[@id='simpleShareMenu']//span[normalize-space(text())='Copy URL']");
	By URL_COPIED = By.xpath("//div[@id='simpleShareMenu']//span[normalize-space(text())='URL Copied!']");
	By ENLARGE_PARTICIPANT = By.cssSelector("button.enlargeVideo");
	By clientAudioTag = By.cssSelector("#videos-wrapper audio");
	By ENLARGE_VIDEO = By.cssSelector("div.enlarge-video video.remote-video");
	By LAYOUT_CONTROL = By.cssSelector("div#meetingLayoutControl");
	By PRESENTATION_MODE = By.xpath("//div[@id='meetingLayoutControl']//span[normalize-space(text())='Presentation Mode']");
	By CONVERSATION_MODE = By.xpath("//div[@id='meetingLayoutControl']//span[normalize-space(text())='Conversation Mode']");
	By TOOLTIP_WRAPPER = By.cssSelector("div#ToolTipWrapper");
	By SLIDE_NAVIGATION = By.cssSelector("div.navigation");
	By HUB_LAYOUT = By.cssSelector("#hub-layout");
	By HUB_USERNAME = By.cssSelector("#userName");
	By HUB_PASSWORD = By.cssSelector(".pwd #password");
	By HUB_SIGNIN_BUTTON = By.cssSelector("button.btn");
	By OPEN_STORYBOOKS_INMEETING = By.xpath("//*[text()='Open storybooks']");
	By STORYBOOK_POPUP = By.cssSelector("div.PopupContainer");
	By MY_STORYBOOKS_BUTTON = By.xpath("//*[text()='My Storybooks']");
	By OPEN_TEST_STORYBOOK = By.cssSelector("[title='Storybook test in voyage'] button");
	By HUB_FAVORITES_BUTTON = By.xpath("//*[text()='Favorites']");
	By HUB_FAVORITES_BUTTON_SELECTED = By.cssSelector("[title='Favorites'].selected");
	By HUB_SESSION_CREATE_BUTTON = By.cssSelector("button.session-btn");
	By HUB_CALEDAR_TEXT = By.xpath("//*[text()='CALENDAR']");
	By HUB_CREATE_SESSION_TEXT = By.xpath("//*[text()='CREATE SESSION']");
	By HUB_SESSION_NAME = By.cssSelector("label + input[type='text']");
	By HUB_SAVE_SESSION = By.cssSelector("button.save-btn");
	By HUB_SESSION_SHOW_BUTTON = By.xpath("//div[contains(@class,'links-wrapper')]/button");
	By HUB_HOST_URL = By.xpath("//label[contains(text(),'Host')]/following-sibling::span");
	By HUB_CLIENT_URL = By.xpath("//label[contains(text(),'Guest')]/following-sibling::span");
	By HUB_AUTO_ADMIT_BUTTON = By.xpath("//label[text()='Auto admit participant to join']");
	By HUB_MUTE_PARTICIPANTS_BUTTON =By.xpath("//label[text()='Mute participants audio upon entry']");
	By HUB_ADD_STORYBOOKS = By.xpath("//div[text()='Add Storybook']");
	By HUB_SESSIONTO_STORYBOOKS_PAGE = By.xpath("//h2[text()='Storybooks']");
	By HUB_SESSION_STORYBOOKS_OK_BUTTON = By.xpath("//button[text()='Ok']");
}
